version: "3.8"
services:
  anythink-backend-node:
    build: ./backend
    container_name: anythink-backend-node
    command: sh -c "cd backend && npm install && npm run build && npm run dev"

    environment:
      - NODE_ENV=development
      - PORT=3000
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
      - ENGINE_WILCO_AI_URL=${ENGINE_WILCO_AI_URL}

    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/backend/node_modules
    ports:
      - "3000:3000"

  anythink-frontend-react:
    build: ./frontend
    container_name: anythink-frontend-react
    command: sh -c "cd frontend && /wait-for-it.sh anythink-backend-node:3000 -t 120 --strict -- curl --head -X GET --retry 30 --retry-connrefused --retry-delay 1 anythink-backend-node:3000/api/ping && npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_BACKEND_URL=${CODESPACE_BACKEND_URL:-http://localhost:3000}
      - WDS_SOCKET_PORT=${CODESPACE_WDS_SOCKET_PORT:-3001}

    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/frontend/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - "anythink-backend-node"

  anythink-ack:
    image: public.ecr.aws/v0a2l7y2/wilco/anythink-ack:latest
    container_name: anythink-ack
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - CODESPACE_NAME=$CODESPACE_NAME
      - APP_NAME=MongoDB RAG Chat
    depends_on:
      - "anythink-frontend-react"

